(require errortrace)
(require racket/trace)

(display "Concatenate two lists (2 8 4 5 6 1) (2 8 4 5 6 1): ")
(define (concatena lista1 lista2)
    (if (null? (car lista1))
        (if (null? (car lista2))
            '() '()
            (if (list? (car lista2)) 
                (concatena lista1 (car lista2))
                (cons (concatena lista1 (cdr lista2) (car lista2)))
            )
            
        )
        (if (list? (car lista1))
            (concatena (car lista1) lista2)
            (cons (car lista1) (concatena (cdr lista1) lista2))
        )
    )
)
(display (concatena '(2 8 4 5 6 1) '(2 8 4 5 6 1)))
(newline)